######
# This is example of config file for slacker.
# There are two sections:
#   * default: this is default options for sending message to slack.
#   * rules: list of rules for matching email message. Currently 'from',
#            'to' and 'subject' fields are supported. Their values can be
#            regexp to match corresponding email field.
#
# Each rule in list tested in order. First matched rule is used to update
# values from 'default' section with its 'options' subsection.
######

default:
    icon_url: ''
    url: "https://hooks.slack.com/services/"
    debug: false
    format: "subject: %(subject)s; body: %(body)s"  ## default slack message format
